### ISSUE TITLE
generate crds using kubebuilder instead of manully editing

### ISSUE THREAD

**Issue by llhuii** [kubeedge/sedna#10]
see the kubebuilder [generating-crd](https://book.kubebuilder.io/reference/generating-crd.html).

**Comment by khalid-davis** [comment]
you mean using kuebuilder to refactor the code of sedna?

**Comment by llhuii** [comment]
since controller-gen doesn't support float64(see https://github.com/kubernetes-sigs/controller-tools/issues/245), and we have float64 in incremental-learning job crd, to be done for this.

**Comment by llhuii** [comment]
> you mean using kuebuilder to refactor the code of sedna?

no, just the definitions of CRs(i.e. the directory https://github.com/kubeedge/sedna/tree/main/build/crds/sedna).

**Comment by llhuii** [comment]
> since controller-gen doesn't support float(see [kubernetes-sigs/controller-tools#245](https://github.com/kubernetes-sigs/controller-tools/issues/245)), and we have float64 in incremental-learning job crd, we need to use the option `allowDangerousTypes` to surround this.
> i.e. `controller-gen crd:crdVersions=v1,allowDangerousTypes=true ...`

just simple look, we could also use `resource.Quantity`, but it would need more code work.

**Comment by llhuii** [comment]
close this one since #11 cherry pick into #33
