### ISSUE TITLE
decouple collaboration feature code and public code

### ISSUE THREAD

**Issue by cgafool** [kubeedge/sedna#102]
**What would you like to be added/modified**:
1. Partitioning folders  at "sedna/pkg/globalmanager/"  by collaboration feature  and place the corresponding code.  
2. Partitioning folders  at "sedna/pkg/localcontroller/"  by collaboration feature  and place the corresponding code.  
3. Decoupling upstream file by  collaboration feature and put  the corresponding code into  the  collaboration feature  fold
4.  Decoupling downsteam file by  collaboration feature and put  the corresponding code into  the  collaboration feature  fold
5.  Any other modifications after decoupling

**Why is this needed**:
Currently, multiple collaboration features are available, and more collaboration features may be available in the future. Decoupling facilitates the development of the developer ecosystem, Such as after decoupling, developers can easily integrate more features.

**Comment by llhuii** [comment]
## Downstream refactor
#### Why is this needed:
Current downstream implementation is that all features synchronization from GM to LC are placed into the downstream.go file, its problem is when a new feature is to added, the developer needs edit this file again. So here want to place all logics of a new feature into a new folder or file.

#### Propose solution:
downstream.go provides the simple interface:
```go
type syncFunc func(eventType watch.EventType, obj interface{}) error
// Add the kind of custom resource(obj), and the syncFunc
Add(object interface{}, syncFunc)
```
Each AI features just calls this Add function to register itself.

**Comment by llhuii** [comment]
## Upstream refactor
Upstream is used to process all synergy AI features update from LC(Local Controller), then update the status of the corresponding objects.
#### Why is this needed:
Similar with downstream implementation, upstream implementation is that all process logic are placed into the upstream.go file, its problem is when a new feature is to added, the developer needs to edit this upstream.go again. 
Here want to place all logics of a new feature into a new folder or file without knowing the upstream.go.

#### Propose solution:
upstream.go provides the simple interface:
```go
type updateHandler func(namespace, name, operation string, content []byte) error
// Add specified kind of custom resource, and the updateHandler to be called
Add(kind string, updateHandler updateHandler)
```
Each AI feature just calls this Add function to register itself to upstream.
