### ISSUE TITLE
Feature worker spec support configmap

### ISSUE THREAD

**Issue by cgafool** [kubeedge/sedna#103]
**What would you like to be added/modified**:
Feature worker spec configuration information can be injected through the configmap or  environment variables. （Currently, it is an environment variable.）

**Why is this needed**:
Developers have built-in containers on the Worker. The ConfigMap is equivalent to the configuration file of the native application. There can be one or more configuration files.
After the container is started, the container obtains the ConfigMap content from the host machine, generates a local file, and maps the file to a specified directory in the container as a volume.
Applications in the container read the configuration files in the container-specific directory in the original manner.
For a container, the configuration file is packaged in a specific directory inside the container. The entire process does not intrude on applications.

**Comment by llhuii** [comment]
AFAIU, the worker configurations can be categoried into two cases:
1. managed by sedna system(specifically the component GM): e.g. dataset/model/hard-example-config, etc.
2. managed by worker: e.g. batch_size for training worker, source_video_url for inference worker, etc.

So this issue only cares the former case, and leaves the other case to the operator by editing the workers' spec template.

**Comment by cgafool** [comment]
close
