### ISSUE TITLE
Incremental learning supports hot model updates.

### ISSUE THREAD

**Issue by cgafool** [kubeedge/sedna#104]
**What would you like to be added/modified**:
Currently, models are updated through restart. infer worker.  Incremental learning is required to support hot model updates rather than only through restart.

**Why is this needed**:
inference engine supports model reloading.  Therefore, it is hoped that dynamic update can be supported.

**Comment by JimmyYang20** [comment]
## How
steps:
1. node that has infer worker says deploy-node
1. GM finds the job wait to deploy, syncs the job info to deploy-node's LC.  This LC checks eval results to trigger deploy model. If satisfied to update model, this LC  downloads the trained model to local volume at deploy-node and sends the ready-to-deploy state to GM. If not satisfied to update model, this LC sends the no-deploy state to GM.
1.  Infer worker's infer adapter monitors deploy model file of local volume. If there has deploy model file and deploy model file has been updated, worker inits secondary infer interface for loading new deploy model file, and stops main interface. Then worker sends the completed-to-deploy state to LC.
2. LC gets the message that contains completed-to-deploy from infer worker and sends it to GM.

**Comment by JimmyYang20** [comment]
![image](https://user-images.githubusercontent.com/25048074/124557360-006e6080-de6c-11eb-8e4c-d793f816c164.png)

**Comment by JimmyYang20** [comment]
![image](https://user-images.githubusercontent.com/25048074/124557416-111ed680-de6c-11eb-8417-2b4e570c4010.png)

**Comment by JimmyYang20** [comment]
![截图](https://user-images.githubusercontent.com/25048074/124561299-5218ea00-de70-11eb-9682-8d66d5654db3.PNG)

**Comment by JimmyYang20** [comment]
![截图](https://user-images.githubusercontent.com/25048074/124561353-60ff9c80-de70-11eb-913c-a89ec8c56a6c.PNG)

**Comment by JimmyYang20** [comment]
![image](https://user-images.githubusercontent.com/25048074/124561514-8ee4e100-de70-11eb-8c74-dc1315392003.png)

**Comment by JimmyYang20** [comment]
![截图](https://user-images.githubusercontent.com/25048074/124561833-e97e3d00-de70-11eb-8a44-f95ad66b7268.PNG)

**Comment by JimmyYang20** [comment]
![image](https://user-images.githubusercontent.com/25048074/125585010-d20fbdf3-e835-44d3-8bfb-dbe5118e5eaf.png)

**Comment by JimmyYang20** [comment]
![image](https://user-images.githubusercontent.com/25048074/125585093-e6e62475-4f1f-4914-b374-1c387faf6a8a.png)

**Comment by llhuii** [comment]
@JimmyYang20 Please provide the interface between LC and LIB.

**Comment by JimmyYang20** [comment]
Add optional the following fields in job spec:
```yaml
deploySpec:
  model:
    hotUpdateEnabled: true
    pollPeriodSeconds: 60  # default value is 60
```

**Comment by JimmyYang20** [comment]
## Componet sequence diagram

![](http://www.plantuml.com/plantuml/png/dLFDJjmm4BxxAKQvqcp3BWiqKYia3YqId2ZgPINaZITPW-D9xGbe1RnxatYDicgsLNl8mVFzVFRCvCApTDpMHh1cWt1b2uSrMfO6hb4wgsq5jstJa6CFDwJGm3TYk6kKPFH2D9rS5xgHbk7h3KWFLRrNJAulGJBWapIfxVH9pp45Jf4KDeQsOvhQfrtP4Xty8FU8RahmF212IPPhwH4IGuKqy4IchN5A492Hm2_W5jqJkW7s2o54LKFwfRzo3dvh2-0DmWEjGTkIH5T-Hmkg6uECmsE1fN_SWzdfgaAtkqF0fU5uZh3kOYLhNsfK0W1Wvr7LlOMqtaZ6AF8ikVN018b3gRQ9GECHBF7_cSGdgCx8AX7lDs9f7wFU6wEc6YEwUW_xHGuEVxRekKzGz6mDIJMGsKbjKK4zx5M7ZiSb_0BIpY2SyZye3qGLr6mdO-ABmhbr9aPr1l-WYh7nWizECmRulY1RwchsuCb2gGqAInrciEHyWh6oBycuckJmih8hiIisaZTTAVau7DCDSTeE_ryep9fryc543zWzwnfxrJoR7wVPMJe_XsoUBxDykPWTBxBZ-Lbs2aTPbi7TzqkeFnyjJvRBsSdyDFjqVdvwagp4syg-XJKmH4q_LdHe2zpzPb2JrKpE7tWpKBa_q20RjImw730OjcyZ3_g_lXv01j4QqKBeXPg8TcX8nkdsebcOaTFL9Wvfw3ne-tlCo33iFrgr2ui_2fL1vkEULFLVU1qsV1TeLLkRNm00)

**Comment by JimmyYang20** [comment]
## Lib sequence diagram
![](http://www.plantuml.com/plantuml/png/XLHDRzf04BtlhnZv15A2Uke1gLMgG9fKf4GbKIz8QB77i64zQ-tEKaNAZ--ipGSEINl0ClFntipRvxqAh3t7oYh5XYt230lIC35BcCMwTfu3tBi2BTmwXgUwq8n1gLgQJ6vgJGpP7PNeCKVuxVm6VGOwGAKDTQj-k6MJUNRBRc8Ss5IQNTk8ePjjoEyTcNr1LR6IAVHI1uJCkbnRs3eRAspIxQjIQG2u_9heXa3uf-5LA-zYVTnHIJ0LOHX27hr7uiCqyALfE_plzHK6kDn3UkJe2N2Vxa1fQy_m1jRfejS7Tf3Ue4gBAQKj0z8MxgUZyMHnEtrSF3sClZsEmGJ87dt4h5TWgQFb9dAZRS2ilsSJCOJEesQ4KwM0rn8iBi1G7Hb4KLqXeqyOqZfGvAJ3czLQ-Ylz0lbQqmhVoiqETBFDKkSRA2FbIbddQYMyYRuLUoZTAFbceqNkg3IhmNDm1AMn2CiNY8rlG9H0S6KRDWIdXmUuHVy2dp-5tN0MInwsBOOO_LPAJJZHwc4waSVurzrqj9YDhwS_HxCBE6ebK8CvVJ1Jz7kmC-4NWdHpzttG7irQXu_sUdtzA9EQbeYqsxj8SXsycEJS9KwybQHkWqTB9QcafNDMOib_E7HE4kWwBWKPgrgAqy6_TUMStelkYa_1vYIh8YCaiDP-hVyEdq8Zndw9m9fZw6Mvg-hKLcGNa9NQM7dhDyecY8sXeh6reTnZXSGY3cfFXbQIpyw5yvZkf0Nhi5aOAbshN40gtkDFkScrakpPxxY2DdJOGOAjmLEqovm44KRqI3ds-l__tckFXScvkJVEcGvG4WZHSZlKbJpJPVmN)

**Comment by JimmyYang20** [comment]
## The interface between LC and LIB

api: http://\<LC-IP:Port address\>/sedna/workers/\<worker-name\>/info
example: http://localhost:9100/sedna/workers/inferworker-fm87v/info

message body:
```json
{
"name": "<worker-name>",
"namespace":  "default",
"kind": "inference",
"status": "completed",
"ownerName": "<job-name>",
"ownerKind": "<job-kind>"
}
```

**Comment by 15926273249** [comment]
@JimmyYang20  how to find the localhost ip and worker-name and is there any other processes to get the message?

**Comment by JimmyYang20** [comment]
@15926273249 GM cat get node name of pod(worker) by using client-go
