### ISSUE TITLE
he ***trainingWorks*** design in federatedlearningjob.yaml

### ISSUE THREAD

**Issue by hardwind-wang** [kubeedge/sedna#112]
Hi,  i do not quite understand the yaml design here. why are the 2 ***dataset*** sections and the 2 ***template*** sections in ***trainingWorkers*** here? 

I guess what you mean is 2 edges with different datasets and different configurations. if this is the case, it makes more sense for me to have 2 ***worker*** sections under the ***trainingWorks*** and assign the dataset and template to the ***worker***

https://github.com/kubeedge/sedna/blob/343544fb8cc0a8dae561921274ddc286320f4026/build/crd-samples/sedna/federatedlearningjob_v1alpha1.yaml#L22-L60

**Comment by llhuii** [comment]
> if this is the case, it makes more sense for me to have 2 worker sections under the trainingWorks and assign the dataset and template to the worker

Hi, if I understand it correctly, `federatedlearningjob.yaml` is indeed what you say, i.e. `trainingWorks` is an array with element having two fields `dataset`, and `template`:
```py
[
    {
        "dataset": {
            "name": "dataset1"
        },
        "template": {}
    },
    {
        "dataset": {
            "name": "dataset2"
        },
        "template": {}
    }
]
```

**Comment by llhuii** [comment]
/close
too long inactivity, reopen it if you have any other question.
