### ISSUE TITLE
Kubeflow vs. Sedna

### ISSUE THREAD

**Issue by vcozzolino** [kubeedge/sedna#114]
I'm trying to understand the differences between Kubleflow and Sedna+KubeEdge. For the sake of simplicity, I will report here the relative (shortened) definitions:

- **Kubeflow**. Kubeflow is an end-to-end Machine Learning (ML) platform for Kubernetes, it provides components for each stage in the ML lifecycle, from exploration through to training and deployment.
- **Sedna**. Sedna is an edge-cloud synergy AI project incubated in KubeEdge SIG AI. Benefiting from the edge-cloud synergy capabilities provided by KubeEdge, Sedna can implement across edge-cloud collaborative training and collaborative inference capabilities, such as joint inference, incremental learning, federated learning, and lifelong learning.

Let start with the main differences I know of:
- Sedna supports the edge-cloud (logical) abstration through KubeEdge with also new CRDs which simplify and support ML/AI workflows. 
- KubeEdge is lightweight compared to Kubernetes (on which Kubeflow runs).
- KubeEdge helps in situations where there is no connectivity (cloud is offline).

However, and please correct me if I'm wrong, I have some doubts:
- It appears that Kubleflow is also designed to be deployable on edge devices as reported [here](https://juju.is/blog/deploying-kubeflow-everywhere) by using microk8s and running a reduced stack/bundle. Wouldn't this in part show the compatibility of Kubeflow with edge devices? The RAM requirements are still pretty high, but this shouldn't be a huge problem if we are actually running ML considering the size of the models loaded in memory **and** if you have multiple models.
- Wouldn't it be possible to provide the edge-cloud abstraction by using node labelling/pod affinity directly in Kubernetes? For this purpose, is it _really_ needed Kubeedge?
- I have the feeling the Kubeflow can offer a simplified deployment of ML workflows because it builds directly on top of K8s. From a system perspective, it's more straightforward because it doesn't depend on another framework (such as KubeEdge).

I hope this is enough to start a discussion :)

**Comment by llhuii** [comment]
Hi, thank you for your great analysis!

Sedna is aimed at edge-cloud collaborative training/inference features, it can be built on top of kubeflow.
But we find that kubeflow can't satisfy sedna's requirements for the below views:
1. **edge**: In theory edge-compute platforms like kubeedge are not needed for sedna. But in practice 
  kubeeedge need to be involved, qnd kubeflow serving depends knative and then istio which kubeedge can't support so far.
2. the collaborative features are some workflows with fixed patterns: 
   1) kubeflow pipline based on argo does not support that batch-job and long-running serving within one workflow.
   2) kubeflow pipline does not support that workload runs only under specified conditions(e.g. in incremental learning feature the train workerload only run when labeled samples is enough) and loop.
   3) kubeflow training does not support with federated-learning. In current kubeflow, multi framework training is implemented separately by crd/operators, i.e. TFJob/MPIJob/PyJob, 
      althought these operators can be reused, but a custom operator for federated learning is still needed.
   4) kubeflow serving does not support multi model joint inference, e.g. for joint inference serving.

**Comment by llhuii** [comment]
And for this your doubt:
> Wouldn't it be possible to provide the edge-cloud abstraction by using node labelling/pod affinity directly in Kubernetes? For this purpose, is it really needed Kubeedge?

You are right. Indeed sedna does like what you say, and is not aware of kubeedge existence.

**Comment by llhuii** [comment]
So for more simplicity, flexibility and controllability, we decided that we implement these edge-cloud collaborative training/inference features throught crd/operators. And in the future, we can introduce and reuse kubeflow features into sedna.

**Comment by llhuii** [comment]
/close
if any question, feel free open it
