### ISSUE TITLE
`numberOfSamples` in dataset has been updated periodly even though the real data store no update

### ISSUE THREAD

**Issue by llhuii** [kubeedge/sedna#136]
**What happened**:
```sh
kubectl get dataset d1 -o yaml |grep -A3 ^status
sleep 15; echo after sleep
kubectl get dataset d1 -o yaml |grep -A3 ^status
```
output: 
![image](https://user-images.githubusercontent.com/419660/127124331-50bff908-8aa9-4509-a14f-680c087ca7fb.png)

**What you expected to happen**:
Because the real data store of this dataset has no update, I expect that no update in dataset `d1`
**How to reproduce it (as minimally and precisely as possible)**:
1. login the vm named edge-node which has been joined by kubeedge, execute this command: `seq 100 > /data.txt`
1. create the dataset by kubectl command
    ```sh
    kubectl create - <<EOF
    apiVersion: sedna.io/v1alpha1
    kind: Dataset
    metadata:
      name: d1
    spec:
      url: "/data.txt"
      format: "txt"
      nodeName: "edge-node"
    EOF
    ```
1. show the status of dataset d1 by kubectl get: `kubectl get dataset d1 -o yaml |grep -A3 ^status`

**Anything else we need to know?**:

**Environment**:
<details><summary>Sedna Version</summary>

```console
$ kubectl get -n sedna deploy gm -o jsonpath='{.spec.template.spec.containers[0].image}'
# paste output here

$ kubectl get -n sedna ds lc -o jsonpath='{.spec.template.spec.containers[0].image}'
# paste output here
kubeedge/sedna-lc:v0.3.0
```

</details>

<details><summary>Kubernets Version</summary>

```console
$ kubectl version
# paste output here
```

</details>

<details><summary>KubeEdge Version</summary>

```console
$ cloudcore --version
# paste output here

$ edgecore --version
# paste output here
```

</details>

**CloudSide Environment**:
<details><summary>Hardware configuration</summary>

```console
$ lscpu
# paste output here
```

</details>

<details><summary>OS</summary>

```console
$ cat /etc/os-release
# paste output here
```

</details>

<details><summary>Kernel</summary>

```console
$ uname -a
# paste output here
```

</details>

<details><summary>Others</summary>
</details>

**EdgeSide Environment**:
<details><summary>Hardware configuration</summary>

```console
$ lscpu
# paste output here
```

</details>

<details><summary>OS</summary>

```console
$ cat /etc/os-release
# paste output here
```

</details>

<details><summary>Kernel</summary>

```console
$ uname -a
# paste output here
```

</details>

<details><summary>Others</summary>
</details>

**Comment by JimmyYang20** [comment]
fix #137
