### ISSUE TITLE
Add contributing docs

### ISSUE THREAD

**Issue by EnfangCui** [kubeedge/sedna#144]
The contributing docs are needed for people who are interested in being a contributor  in developing the sedna. The contributing docs should include:

- Contributor workflow
- K8S controller development tools, such as kubebuilder or code-genetator
- Code test steps and tools
- Format of the commit message

etc.

Part of the content may refer to https://github.com/kubeedge/kubeedge/blob/master/CONTRIBUTING.md

**Comment by llhuii** [comment]
relative issue #126 
the tracking issue #3

**Comment by llhuii** [comment]
@EnfangCui can you help to review #148?
