### ISSUE TITLE
A local sedna (just like minikube for k8s) is needed

### ISSUE THREAD

**Issue by yunzhe99** [kubeedge/sedna#181]
What would you like to be added/modified: 
    I think Sedna will be accepted by more people if there is **a local version of Sedna**. This version should be able to run on one server and then use virtual machines to simulate the entire cluster. More importantly, this version should be able to be run quickly **from scratch**, with support for rapid modification and experimentation. I believe that this will help more researchers with AI backgrounds to really use Sedna.

Why is this needed:
    Sedna is a project for k8s researchers and AI researchers. Sedna's support for AI has attracted many AI researchers to try using Sedna, especially edge AI researchers, which will significantly reduce their research costs. However, the current version of Sedna requires relatively complete installation of k8s and KubeEdge on multiple devices. Sedna installation is challenging for many researchers with only an AI background, considering the differences between different software environments on different devices. As far as I know, many interested developers are stuck with the installation and can't even get past the example provided. So I think a local version of Sedna is needed for further promotion.

**Comment by llhuii** [comment]
Good suggestion. We also have some dicussion, and I will be focused on this in this month.
/assign
Note: A local up script based on the latest main branch is [here](https://github.com/kubeedge/sedna/blob/main/docs/setup/local-up.md), maybe helpful for you even though it is friendly to the end users.

**Comment by llhuii** [comment]
Now we can create a k8s cluster with kubeedge and sedna locally exactly do what kind do:
1. Multi edge nodes with NUM_EDGE_WORKERS
2. Multi cloud workers except master node with NUM_CLOUD_WORKERS

It just requires docker, and kind.

You can try it:
```bash
# default one edge node
curl https://raw.githubusercontent.com/llhuii/sedna/allinone-script/scripts/installation/minisedna.sh | bash -

# two edge nodes
# curl https://raw.githubusercontent.com/llhuii/sedna/allinone-script/scripts/installation/minisedna.sh | NUM_EDGE_WORKERS=2 bash -
```

Then you can play it with `kubectl`.


Clean it:
```bash
curl https://raw.githubusercontent.com/llhuii/sedna/allinone-script/scripts/installation/minisedna.sh | bash /dev/stdin clean
```

More things to be fixed:
- [ ] Fix cni of edge node
- [ ] Install kind if missing

**Comment by llhuii** [comment]
You can try it using this katacoda course, https://www.katacoda.com/sedna-ai/scenarios/all-in-one
