### ISSUE TITLE
It always gets stuck in this place, can you tell me what to do? 

### ISSUE THREAD

**Issue by Liu-JJ97** [kubeedge/sedna#191]
namespace/sedna created
node/master labeled
customresourcedefinition.apiextensions.k8s.io/datasets.sedna.io created
customresourcedefinition.apiextensions.k8s.io/federatedlearningjobs.sedna.io cre                                                                            ated
customresourcedefinition.apiextensions.k8s.io/incrementallearningjobs.sedna.io c                                                                            reated
customresourcedefinition.apiextensions.k8s.io/jointinferenceservices.sedna.io created
Error from server (Timeout): error when creating "build/crds/sedna.io_lifelonglearningjobs.yaml": the server was unable to return a response in the time allotted, but may still be processing the request (post customresourcedefinitions.apiextensions.k8s.io)
Error from server (Timeout): error when creating "build/crds/sedna.io_models.yaml": Timeout: request did not complete within requested timeout 34s

**Comment by JoeyHwong-gk** [comment]
Are you using any proxies? put more details about your installtion

**Comment by Liu-JJ97** [comment]
Yes, I used a proxy, I downloaded the source code to the local, and then used the command to execute. If I don’t use the proxy, the install.sh file cannot be downloaded. Is it possible to execute the install.sh file locally? How should I execute it?

**Comment by JoeyHwong-gk** [comment]
Try the following solutions and provide your feedback please.
```bash
# upload sedna to your server first

export SEDNA_ROOT=/home/master/sedna

cd $SEDNA_ROOT/ scripts/installation/
cat install.sh | SEDNA_GM_NODE=$SEDNA_GM_NODE SEDNA_ACTION=create bash -

```

**Comment by Liu-JJ97** [comment]
error: error when creating "build/crds/sedna.io_incrementallearningjobs.yaml": Post https://192.168.137.6:6443/apis/apiextensions.k8s.io/v1/customresourcedefinitions: stream error: stream ID 7; INTERNAL_ERROR

**Comment by llhuii** [comment]
> Error from server: error when creating "build/crds/sedna.io_jointinferenceservices.yaml": etcdserver: request timed out

@Liu-JJ97 looks like api-server has problem to connect etcd. Can you check your etcd server?

**Comment by llhuii** [comment]
https://github.com/etcd-io/etcd/issues/11809
https://github.com/kubernetes-sigs/kind/issues/717#issuecomment-512507692

Look like it is the disk IO issue

**Comment by Liu-JJ97** [comment]
> 请尝试以下解决方案并提供反馈。
> 
> ```shell
> # 先上传sedna到你的服务器
> 
> 出口SEDNA_ROOT=/home/master/sedna
> 
> cd  $SEDNA_ROOT /scripts/installation/
> cat install.sh | SEDNA_GM_NODE= $SEDNA_GM_NODE SEDNA_ACTION=创建 bash -
> ```

Thank you very much. I closed the proxy and resolved it successfully.

**Comment by Liu-JJ97** [comment]
Thank you very much. I closed the proxy and resolved it successfully.

**Comment by llhuii** [comment]
Thanks for the feedback.
/close
