### ISSUE TITLE
failed to run jointinferenceservice demo

### ISSUE THREAD

**Issue by TymonXie** [kubeedge/sedna#24]
when i run jointinferenceservice demo according to the document，the specific issues are as follows:
![image](https://user-images.githubusercontent.com/30067438/111597912-a3419700-8809-11eb-99ca-3f9f8c1b63aa.png)
i can not find sedna-gm.yaml in gm directory

**Comment by TymonXie** [comment]
![image](https://user-images.githubusercontent.com/30067438/111598335-15b27700-880a-11eb-8aa4-2da32243a11d.png)
![Uploading image.png…]()

here, mkdir /code/little_model, /code/big_model, but after that i find it changed to /code/little-model, /code/big-model in yaml

**Comment by TymonXie** [comment]
@JimmyYang20 ,hi jimmy yang, can you check them and fix it?

**Comment by llhuii** [comment]
will be updated in next release

**Comment by llhuii** [comment]
/close
fixed in v0.1.0 release
