### ISSUE TITLE
[helmet-detection-inference-example] edge node container cannot access cloud service

### ISSUE THREAD

**Issue by siguoyicl** [kubeedge/sedna#263]
Error occurred while request http://helmet-detection-inference-example-cloud.default:5000/sedna/predict, Msg: HTTPConnectionPool(host='helmet-detection-inference-example-cloud.default', port=5000): Max retries exceeded with url: /sedna/predict (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4df0209470>: Failed to establish a new connection: [Errno -2] Name or service not known',))

**Comment by JoeyHwong-gk** [comment]
Seems to be a problem with dnsPolicy of k8s. ping @JimmyYang20

**Comment by JimmyYang20** [comment]
@siguoyicl 
check edgemesh status  by `kubectl -n kubeedge get pods`
pleases to read  [doc](https://github.com/kubeedge/sedna/blob/main/docs/setup/install.md) in detail and pay more attention to [edgemesh](https://edgemesh.netlify.app/guide/getting-started.html)

**Comment by siguoyicl** [comment]
@JimmyYang20 edgemesh status is all correct.
[root@ke-cloud config]# kubectl -n kubeedge get pods
NAME                              READY   STATUS    RESTARTS   AGE
edgemesh-agent-cloud-9sf2z        1/1     Running   0          26m
edgemesh-agent-edge-8ngkm         1/1     Running   0          26m
edgemesh-agent-edge-nntjp         1/1     Running   0          26m
edgemesh-server-cbb7d976b-h7wzn   1/1     Running   0          31m

**Comment by siguoyicl** [comment]
@jaypume the logs for edgemesh-server is as follows:
`I0113 03:13:17.794671       1 config.go:37] Fetch public IP: 139.207.140.117
I0113 03:13:17.795070       1 server.go:47] Version: v0.0.0-master+$Format:%H$
I0113 03:13:17.795110       1 server.go:79] [1] New informers manager
W0113 03:13:17.795129       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0113 03:13:17.795658       1 server.go:86] [2] Register beehive modules
I0113 03:13:17.795719       1 manager.go:33] Use noCaManager to handle security
I0113 03:13:17.795736       1 nocamanager.go:38] Private key does not exist, generate a new one
I0113 03:13:17.798765       1 module.go:34] Module tunnelserver registered successfully
I0113 03:13:17.798779       1 server.go:92] [3] Start informers manager
W0113 03:13:17.798902       1 shared_informer.go:372] The sharedIndexInformer has started, run more than once is not allowed
I0113 03:13:17.899230       1 server.go:96] [4] Start all modules
I0113 03:13:17.899425       1 core.go:24] Starting module tunnelserver
I0113 03:13:17.899568       1 tunnel.go:12] Start tunnel server success
I0113 03:13:17.899739       1 tunnel.go:14] Tunnel server addr : /ip4/192.168.150.130/tcp/20004/p2p/QmcPJzo7ZLMfTN162qHHZ6LkG98eYXmF5w8S3GmTRgN4hp
I0113 03:13:17.899870       1 tunnel.go:14] Tunnel server addr : /ip4/127.0.0.1/tcp/20004/p2p/QmcPJzo7ZLMfTN162qHHZ6LkG98eYXmF5w8S3GmTRgN4hp
I0113 03:13:17.899892       1 tunnel.go:14] Tunnel server addr : /ip4/139.207.140.117/tcp/20004/p2p/QmcPJzo7ZLMfTN162qHHZ6LkG98eYXmF5w8S3GmTRgN4hp
I0113 03:13:17.905929       1 tunnel.go:22] success update [edgemeshserver] addr [/ip4/192.168.150.130/tcp/20004 /ip4/127.0.0.1/tcp/20004 /ip4/139.207.140.117/tcp/20004] to secret`

**Comment by siguoyicl** [comment]
@jaypume @JimmyYang20 Thanks a lot. I have found the problem, in the container in edgenode, the config file /etc/resolv.conf is incorrect, it is shown as follows:
`
# Generated by NetworkManager
search localdomain
nameserver 192.168.150.2
`
so I modify the config, add edgemesh0 into it
`
# Generated by NetworkManager
nameserver 169.254.96.16
search edgemesh-test.svc.cluster.local svc.cluster.local cluster.local localdomain
options ndots:5
`
After done this, the example works.
