### ISSUE TITLE
An error occurred while installing Sedna

### ISSUE THREAD

**Issue by 916264367** [kubeedge/sedna#278]
**What happened**:
An error occurred while installing Sedna, like this:
![image](https://user-images.githubusercontent.com/51771785/156088427-8f6be133-ff06-48fa-9622-8c588832ef28.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
<details><summary>Sedna Version</summary>
Ubuntu 20.04
K8s 1.21.3
Kubeedge 1.9.1
EdgeMesh running

If you want other details, you can tell me in the comments area.

```console
$ kubectl get -n sedna deploy gm -o jsonpath='{.spec.template.spec.containers[0].image}'
# paste output here

$ kubectl get -n sedna ds lc -o jsonpath='{.spec.template.spec.containers[0].image}'
# paste output here
```

</details>

<details><summary>Kubernets Version</summary>

```console
$ kubectl version
# paste output here
```

</details>

<details><summary>KubeEdge Version</summary>

```console
$ cloudcore --version
# paste output here

$ edgecore --version
# paste output here
```

</details>

**CloudSide Environment**:
<details><summary>Hardware configuration</summary>

```console
$ lscpu
# paste output here
```

</details>

<details><summary>OS</summary>

```console
$ cat /etc/os-release
# paste output here
```

</details>

<details><summary>Kernel</summary>

```console
$ uname -a
# paste output here
```

</details>

<details><summary>Others</summary>
</details>

**EdgeSide Environment**:
<details><summary>Hardware configuration</summary>

```console
$ lscpu
# paste output here
```

</details>

<details><summary>OS</summary>

```console
$ cat /etc/os-release
# paste output here
```

</details>

<details><summary>Kernel</summary>

```console
$ uname -a
# paste output here
```

</details>

<details><summary>Others</summary>
</details>

**Comment by 916264367** [comment]
![image](https://user-images.githubusercontent.com/51771785/156135638-f56cd1cb-e1cb-40a5-b598-ca0060ad3a94.png)
![image](https://user-images.githubusercontent.com/51771785/156135735-538b33ae-92d8-4abf-8d6a-82931752ea7f.png)

**Comment by JoeyHwong-gk** [comment]
[Here](https://github.com/kubeedge/sedna/blob/main/docs/setup/install.md) is the recommended installation guide. 
Based on the consideration of integrated edgemesh, sedna has updated the model of GM deployment, follow #220 for more details.

**Comment by 916264367** [comment]
> [这](https://github.com/kubeedge/sedna/blob/main/docs/setup/install.md)是推荐的安装指南。 基于集成edgemesh的考虑，sedna更新了GM部署的模型，更多详情请关注#220。

I followed your instructions, But I still encountered the same mistake.
![image](https://user-images.githubusercontent.com/51771785/156278940-13ba4937-a772-469f-bb05-235f97f8975f.png)
![image](https://user-images.githubusercontent.com/51771785/156279049-64ddc5cc-c5d8-450b-8fd8-2036ff95a463.png)

**Comment by 916264367** [comment]
> [这](https://github.com/kubeedge/sedna/blob/main/docs/setup/install.md)是推荐的安装指南。 基于集成edgemesh的考虑，sedna更新了GM部署的模型，更多详情请关注#220。

At the edge, I checked docker's log, 
![image](https://user-images.githubusercontent.com/51771785/156279979-fb3785bd-18cd-4a52-ace3-380e051257db.png)
![image](https://user-images.githubusercontent.com/51771785/156280017-5e7fb352-7234-4ec3-b78c-174f3b9c63a4.png)

**Comment by 916264367** [comment]
> [这](https://github.com/kubeedge/sedna/blob/main/docs/setup/install.md)是推荐的安装指南。 基于集成edgemesh的考虑，sedna更新了GM部署的模型，更多详情请关注#220。

**Comment by JimmyYang20** [comment]
@916264367 
Have you tried setting KUBE_CONFIG_PATH?  please check it !  if not , do
`export KUBE_CONFIG_PATH=~/.kube/config`

**Comment by 916264367** [comment]
> @916264367 Have you tried setting KUBE_CONFIG_PATH? please check it ! if not , do `export KUBE_CONFIG_PATH=~/.kube/config`
I'll follow your tips,
![1](https://user-images.githubusercontent.com/51771785/156484175-1ae4a4d0-5142-421d-8d83-5d00124a630b.png)
![2](https://user-images.githubusercontent.com/51771785/156484180-871c7511-8d0e-4b17-a85b-faac3c622a60.png)
It's still that problem.

**Comment by JimmyYang20** [comment]
@916264367 check if k8s config is in ~/.kube/config ?

**Comment by chenjiafu-George** [comment]
> > @916264367 Have you tried setting KUBE_CONFIG_PATH? please check it ! if not , do `export KUBE_CONFIG_PATH=~/.kube/config`
> > I'll follow your tips,
> > ![1](https://user-images.githubusercontent.com/51771785/156484175-1ae4a4d0-5142-421d-8d83-5d00124a630b.png)
> > ![2](https://user-images.githubusercontent.com/51771785/156484180-871c7511-8d0e-4b17-a85b-faac3c622a60.png)
> > It's still that problem.

I also occurredthe same problem, how to solve it?
