### ISSUE TITLE
How can I see the cloud_result and edge_result in the joint inference experiment?

### ISSUE THREAD

**Issue by 916264367** [kubeedge/sedna#280]
**What happened**:
when I execute "ffmpeg -re -i /data/video/video.mp4 -vcodec libx264 -f rtsp rtsp://localhost/video",that is to say the last step in the document, the ouputdir " /joint_inference/output" is empty? why
**What you expected to happen**:
What will it be like? Output picture or execute " ffplay rtsp://localhost/video", It can be recognized by video?
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
<details><summary>Sedna Version</summary>
Kubeedge : v1.9.1
Kubernetes : v1.21.3
sedna : v0.4.3
```console
$ kubectl get -n sedna deploy gm -o jsonpath='{.spec.template.spec.containers[0].image}'
# paste output here

$ kubectl get -n sedna ds lc -o jsonpath='{.spec.template.spec.containers[0].image}'
# paste output here
```

</details>

<details><summary>Kubernets Version</summary>

```console
$ kubectl version
# paste output here
```

</details>

<details><summary>KubeEdge Version</summary>

```console
$ cloudcore --version
# paste output here

$ edgecore --version
# paste output here
```

</details>

**CloudSide Environment**:
<details><summary>Hardware configuration</summary>

```console
$ lscpu
# paste output here
```

</details>

<details><summary>OS</summary>

```console
$ cat /etc/os-release
# paste output here
```

</details>

<details><summary>Kernel</summary>

```console
$ uname -a
# paste output here
```

</details>

<details><summary>Others</summary>
</details>

**EdgeSide Environment**:
<details><summary>Hardware configuration</summary>

```console
$ lscpu
# paste output here
```

</details>

<details><summary>OS</summary>

```console
$ cat /etc/os-release
# paste output here
```

</details>

<details><summary>Kernel</summary>

```console
$ uname -a
# paste output here
```

</details>

<details><summary>Others</summary>
</details>

**Comment by 916264367** [comment]
![image](https://user-images.githubusercontent.com/51771785/158320448-ac7ce183-4565-4350-b009-d995be1b72af.png)
pod"edge-x4161" there is no events and no logs.
the "cloud-8tmpv" has no logs, but events:
![image](https://user-images.githubusercontent.com/51771785/158320689-66955923-17c0-4b79-a18f-6ba87a49c5e9.png)

**Comment by JoeyHwong-gk** [comment]
It seems that both inference workers run errors, would  you mind providing some details?

**Comment by 916264367** [comment]
> 似乎两个推理工作者都运行错误，您介意提供一些细节吗？
Thank you. The previous problem has been solved. Now, edge is okay, but the master has a problem:
![image](https://user-images.githubusercontent.com/51771785/159702424-753702d1-c6b4-4030-b07e-519a31d2afdb.png)
[2022-03-23 12:41:05,321] base.py(79) [INFO] - Start sedna server over http://10.244.0.6:5000
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/uvicorn/server.py", line 69, in run
    return asyncio.get_event_loop().run_until_complete(self.serve(sockets=sockets))
  File "/usr/lib/python3.6/asyncio/events.py", line 694, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "/usr/lib/python3.6/asyncio/events.py", line 602, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-1'.

I use images from dockerhub:
docker pull kubeedge/sedna-example-joint-inference-helmet-detection-big:v0.4.0

**Comment by JoeyHwong-gk** [comment]
Seems to have found the solution on #289 , and this issue should be closed.

**Comment by 916264367** [comment]
> 看来您已经在#289上找到了解决方案，应该关闭此问题。
thank you very much

**Comment by yxlbetter** [comment]
Hello, may I ask how you solved the pod"edge-x4161" error problem, I also encountered the same problem, the container of my small model crashbackoff at the beginning of operation, and I could not print logs through "kubectl logs", and connect refused would be displayed? Can you tell me how to solve it?

**Comment by yxlbetter** [comment]
> Hello, may I ask how you solved the pod"edge-x4161" error problem, I also encountered the same problem, the container of my small model crashbackoff at the beginning of operation, and I could not print logs through "kubectl logs", and connect refused would be displayed? Can you tell me how to solve it?

@JoeyHwong-gk @916264367 help me please
