### ISSUE TITLE
Joint Inference Service is failed on the agent

### ISSUE THREAD

**Issue by zz952332446** [kubeedge/sedna#290]
I am deploying Example1：[Using Joint Inference Service in Helmet Detection Scenario](https://github.com/kubeedge/sedna/blob/main/examples/joint_inference/helmet_detection_inference/README.md).

In the last step `Create joint inference service`, master is okay, but joint-inference-helmet-detection-little can't work on the edge: you can see there is no pod on the edge(I have already had  the big and little images locally and version is v0.4.3)
![image](https://user-images.githubusercontent.com/34162360/159713248-581a9a96-a421-45d8-b5d3-72faae807a9c.png)

`kubectl describe ji`：

```
  Edge Worker:
    Hard Example Mining:
      Name:  IBT
      Parameters:
        Key:    threshold_img
        Value:  0.9
        Key:    threshold_box
        Value:  0.9
    Model:
      Name:  helmet-detection-inference-little-model
    Template:
      Spec:
        Containers:
          Env:
            Name:             input_shape
            Value:            416,736
            Name:             video_url
            Value:            rtsp://localhost/video
            Name:             all_examples_inference_output
            Value:            /data/output
            Name:             hard_example_cloud_inference_output
            Value:            /data/hard_example_cloud_inference_output
            Name:             hard_example_edge_inference_output
            Value:            /data/hard_example_edge_inference_output
          Image:              kubeedge/sedna-example-joint-inference-helmet-detection-little:v0.4.3
          Image Pull Policy:  IfNotPresent
          Name:               little-model
          Resources:
            Limits:
              Memory:  2Gi
            Requests:
              Cpu:     100m
              Memory:  64M
          Volume Mounts:
            Mount Path:  /data/
            Name:        outputdir
        Node Name:       wspn2
        Volumes:
          Host Path:
            Path:  /joint_inference/output
            Type:  Directory
          Name:    outputdir
Status:
  Active:  1
  Conditions:
    Last Heartbeat Time:   2022-03-23T13:34:59Z
    Last Transition Time:  2022-03-23T13:34:59Z
    Status:                True
    Type:                  Running
    Last Heartbeat Time:   2022-03-23T13:34:59Z
    Last Transition Time:  2022-03-23T13:34:59Z
    Message:               the worker of service failed
    Reason:                workerFailed
    Status:                True
    Type:                  Failed
  Failed:                  1
  Start Time:              2022-03-23T13:34:59Z
Events:                    <none>

```

on the edge, edgemesh and sedna are okay, but there is no joint-inference-helmet-detection-little
![image](https://user-images.githubusercontent.com/34162360/159713866-26eb3118-8293-41a6-a8ce-52f4fe3366c5.png)

```
docker logs k8s_lc_lc-zlrzg_sedna
```
![image](https://user-images.githubusercontent.com/34162360/159714209-7dcdea2e-4261-44df-a30b-144df204f62a.png)

I have already tried to uninstall sdena and restart it again, the problem still exists.

**Comment by JoeyHwong-gk** [comment]
I'd like to know more about it. would you mind providing more logs?

```console
 kubectl logs -f <your gm pod name> -n sedna 
```

```console
df -h  #  on edge node
```

```console
cloudcore --version

edgecore --version
```

**Comment by zz952332446** [comment]
> I'd like to know more about it. would you mind providing more logs?
> 
> ```
>  kubectl logs -f <your gm pod name> -n sedna 
> ```
> 
> ```
> df -h  #  on edge node
> ```
> 
> ```
> cloudcore --version
> 
> edgecore --version
> ```

```
kubectl logs -f <your gm pod name> -n sedna
```
![image](https://user-images.githubusercontent.com/34162360/159820135-b63f7c99-125b-40b0-bab7-188242f2036e.png)


```
cloudcore --version 
```
![image](https://user-images.githubusercontent.com/34162360/159819943-d85cdbf8-f76b-4b9c-b227-c3acef346570.png)


```
edgecore --version
```
![image](https://user-images.githubusercontent.com/34162360/159820001-34647272-8947-4a98-87a5-63500b665833.png)


```
df -h #edge
```
![image](https://user-images.githubusercontent.com/34162360/159819872-cfd7560e-41c9-4465-9360-7c4eba27fafc.png)

**Comment by zz952332446** [comment]
The day before yesterday, joint-inference-helmet-detection-little was okay on the edge, but edge' was disconnect the network yesterday. When the network recovered, I can't deploy joint-inference-helmet-detection-little on the edge anymore.

**Comment by JoeyHwong-gk** [comment]
PTAL @JimmyYang20 @Poorunga

**Comment by zz952332446** [comment]
According to edgecore's log, it said pod already deleted
![image](https://user-images.githubusercontent.com/34162360/159837544-127db928-8c4e-4b24-98e0-4213495bf700.png)

**Comment by zz952332446** [comment]
> According to edgecore's log, it said pod already deleted. under the path `:/var/lib/edged/pods`, no pod of helmet-detection-inference-example ![image](https://user-images.githubusercontent.com/34162360/159837544-127db928-8c4e-4b24-98e0-4213495bf700.png)

**Comment by zz952332446** [comment]
Oh, I closed this issue carelessly just now.

**Comment by talenterj** [comment]
could I ask how you solve this , now i meet the same problem in sedna-v0.5.0

**Comment by zz952332446** [comment]
> could I ask how you solve this , now i meet the same problem in sedna-v0.5.0

I didn't solve this, and I haven't used Sedna from this bug

**Comment by JimmyYang20** [comment]
I'd like to know more about it. would you mind providing more logs?
1. `kubectl get nodes`
2. `kubectl get ji -o yaml`

**Comment by JimmyYang20** [comment]
@talenterj check memory in edge, `free -m`

**Comment by talenterj** [comment]
```
root@edge:/home/cambricon# free -m
              total        used        free      shared  buff/cache   available
Mem:          31958         987       23781           7        7190       30513
Swap:             0           0           0
```

**Comment by JimmyYang20** [comment]
@talenterj 
Is it convenient to send me an online contact? Is it convenient to help you solve the problem online?

**Comment by talenterj** [comment]
qq is ok? 417534634

**Comment by talenterj** [comment]
@JimmyYang20 or which log I should check to solve this problem, lc ,edgemesh nodes shows no error when create service

**Comment by talenterj** [comment]
OK，I solve this problem by check gm logs
```
I0721 04:09:35.631703       1 worker.go:180] pod helmet-detection-inference-example-cloud-dfb4c is created successfully for sedna.io/v1alpha1, Kind=JointInference default/helmet-detection-inference-example
W0721 04:09:35.654432       1 worker.go:220] failed to create service for JointInference default/helmet-detection-inference-example, err:services "helmet-detection-inference-example-cloud" already exists
```

check k8s service `kubectl get svc`
```
NAME                                       TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
helmet-detection-inference-example-cloud   ClusterIP   10.105.223.115   <none>        5000/TCP   6d20h
kubernetes                                 ClusterIP   10.96.0.1        <none>        443/TCP    51d
```
delete svc ` kubectl delete svc helmet-detection-inference-example-cloud` and deploy joint-inferenc is ok。
like this
```
NAMESPACE     NAME                                             READY   STATUS    RESTARTS   AGE     IP                NODE             NOMINATED NODE   READINESS GATES
default       helmet-detection-inference-example-cloud-5bx58   1/1     Running   0          69s     10.244.0.210      cloud.kubeedge   <none>           <none>
default       helmet-detection-inference-example-edge-cffwv    1/1     Running   0          69s     192.168.31.7      edge.cambricon   <none>           <none>
```
