### ISSUE TITLE
wrong url in document

### ISSUE THREAD

**Issue by RyanZhaoXB** [kubeedge/sedna#393]
**What would you like to be documented**:
i found a wrong url in https://sedna.readthedocs.io/en/latest/index/quickstart.html#deploy-sedna

these 3 links are all not found.
![image](https://user-images.githubusercontent.com/100741994/216273997-c96728f1-9cda-4010-94aa-15e07bdbb227.png)

**Comment by JoeyHwong-gk** [comment]
It seems that this [commit](https://github.com/kubeedge/sedna/commit/86839970180bd454ebf08c3faf9135a955105024) imported the wrong path for senda (move  [docs/setup/quick-start.md → docs/index/quick-start.md]).

Looks like an easy fix, would you be willing to submit a pr to fix it？ @RyanZhaoXB
