### ISSUE TITLE
install sedna is a big problem

### ISSUE THREAD

**Issue by Piwriw** [kubeedge/sedna#395]
It is a problem with the [bash](https://github.com/kubeedge/sedna/blob/main/docs/setup/install.md) file when i install sedna. 
In my opinion, It should be solved as soon as possible and provide more installation methods.

**Comment by JoeyHwong-gk** [comment]
Would you mind to provide more information describing the problem you are having with the [bash](https://github.com/kubeedge/sedna/blob/main/docs/setup/install.md) script

**Comment by Piwriw** [comment]
It is alaways timeout in china. What is more，I used [scripts/installation/all-in-one.sh](https://github.com/kubeedge/sedna/blob/1cddd17ef2b2a04bf5fc6a58381c341c110be7fe/scripts/installation/all-in-one.sh) ,it alaways stop in "install kubeedge" .

**Comment by JoeyHwong-gk** [comment]
> It is alaways timeout in china

Very sorry @Piwriw , I think it's cause by the download thread is jammed. Perhaps you can fix it by update your private network. but I'm pretty sure the problem isn't on either sedna's or github's side.

**Comment by Piwriw** [comment]
> 

Thanks for your help， I have try other ways to slove the problem. I will close issues.I used a manual download.It work success.

**Comment by Piwriw** [comment]
> > It is alaways timeout in china
> 
> Very sorry @Piwriw , I think it's cause by the download thread is jammed. Perhaps you can fix it by update your private network. but I'm pretty sure the problem isn't on either sedna's or github's side.

Thanks for your help， I have try other ways to slove the problem. I will close issues.I used a manual download.It work success.

**Comment by 666Yiran-Zhou** [comment]
I'm sorry. I have the same problem as you @Piwriw . I need to run all-in-one.sh when I'm running Quick Start provided by the sedna official documentation. But I also stopped at the kubeedge installation stage. I read the script and found the key problem was this command: 
```
keadm init --kubeedge-version=$version --advertise-address=$CLOUDCORE_ADVERTISE_ADDRESSES
```
This command will download many files. But in the Quick Start example, my cloud node was a docker container named `sedna-mini-control-plane`, which started automatically after installing k8s, I found this container couldn't access the Internet, so it makes sense `keadm init` failed. I'm trying to download manually now,  but so far it hasn't worked. Could you please tell me how to solve this problem in details ? or anybody knows how to config network in `sedna-mini-control-plane`?

**Comment by Piwriw** [comment]
@666Yiran-Zhou Maybe you can try `cluster install`.I use this way.
