### ISSUE TITLE
Join_inference cannot be connected to the cloud for analysis

### ISSUE THREAD

**Issue by Jw-Jm** [kubeedge/sedna#53]
**What happened**:
When I use the example which is joint_inference/helmet_detection_inference, there are some errors in the log
helmet-detection-inference-example-edge-5pg66  logs:
`[2021-04-16 02:32:48,383][sedna.joint_inference.joint_inference][ERROR][124]: send request to http://192.168.2.211:30691 failed, error is HTTPConnectionPool(host='192.168.2.211', port=30691): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efe5409dcf8>: Failed to establish a new connection: [Errno 111] Connection refused',)), retry times: 5
[2021-04-16 02:32:48,384][sedna.joint_inference.joint_inference][WARNING][365]: retrieve cloud infer service failed, use edge result
`

**What you expected to happen**:
The above error does not exist

**How to reproduce it (as minimally and precisely as possible)**:
Just follow the example: https://github.com/kubeedge/sedna/blob/main/examples/joint_inference/helmet_detection_inference/README.md

**Anything else we need to know?**:

**Environment**:
<details><summary>Sedna Version</summary>

```console
$ kubectl get -n sedna deploy gm -o jsonpath='{.spec.template.spec.containers[0].image}'
# paste output here
kubeedge/sedna-gm:v0.1.0
$ kubectl get -n sedna ds lc -o jsonpath='{.spec.template.spec.containers[0].image}'
# paste output here
```
kubeedge/sedna-lc:v0.1.0
</details>

<details><summary>Kubernets Version</summary>

```console
$ kubectl version
# paste output here
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

</details>

<details><summary>KubeEdge Version</summary>

```console
$ cloudcore --version
# paste output here
1.6
$ edgecore --version
# paste output here
```
1.6
</details>

**CloudSide Environment**:
<details><summary>Hardware configuration</summary>

```console
$ lscpu
# paste output here
```

</details>

<details><summary>OS</summary>

```console
$ cat /etc/os-release
# paste output here
```

</details>

<details><summary>Kernel</summary>

```console
$ uname -a
# paste output here
```

</details>

<details><summary>Others</summary>
</details>

**EdgeSide Environment**:
<details><summary>Hardware configuration</summary>

```console
$ lscpu
# paste output here
```

</details>

<details><summary>OS</summary>

```console
$ cat /etc/os-release
# paste output here
```

</details>

<details><summary>Kernel</summary>

```console
$ uname -a
# paste output here
```

</details>

<details><summary>Others</summary>
</details>

**Comment by Jw-Jm** [comment]
add:
[root@node3 ~]# curl  http://192.168.2.211:30691
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>
[root@node3 ~]# curl  http://192.168.2.211:30691
curl: (7) Failed connect to 192.168.2.211:30691; Connection refused

**Comment by llhuii** [comment]
hi, @Jw-Jm thank you for reporting this problem. I have a question for 
> 

> add:
> [root@node3 ~]# curl http://192.168.2.211:30691
> 
> <title>405 Method Not Allowed</title>
> # Method Not Allowed
> The method is not allowed for the requested URL.
> 
> [root@node3 ~]# curl http://192.168.2.211:30691 curl: (7) Failed connect to 192.168.2.211:30691; Connection refused

It seems confusing: first request had the response, and the second had no response. Does the two cases happend sometimes?


## can you upload the log of cloud-worker here?

**Comment by llhuii** [comment]
@Jw-Jm , you can simply get logs of cloud-worker with following command:
```bash
## completion for kubectl 
. <(kubectl completion bash)

kubectl logs helmet-detection-inference-example-Cloud-<hit the TAB key here>
```

**Comment by Jw-Jm** [comment]
@llhuii Thank you for your reply, following is the information required:

```
[root@master3 ~]# kubectl get pod helmet-detection-inference-example-cloud-nw5dc
NAME                                             READY   STATUS    RESTARTS   AGE
helmet-detection-inference-example-cloud-nw5dc   1/1     Running   0          139m
```

tips：A large number of duplicate messages like "POST/HTTP/1.1" 200 - have been deleted

```
[root@master3 ~]# kubectl logs  helmet-detection-inference-example-cloud-nw5dc
2021-04-16 01:17:06.080098: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-04-16 01:17:06.083254: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2904000000 Hz
2021-04-16 01:17:06.083660: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x3b5c270 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-04-16 01:17:06.083682: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
[2021-04-16 01:17:06,977][sedna.joint_inference.joint_inference][INFO][170]: Import yolo model from /home/data/data/big-model/yolov3_darknet.pb end .......
 * Serving Flask app "sedna.joint_inference.joint_inference" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
[2021-04-16 01:17:06,984][werkzeug][INFO][113]:  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2021-04-16 01:24:28.246126: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 38158848 exceeds 10% of system memory.
[2021-04-16 01:24:28,856][werkzeug][INFO][113]: 10.244.0.1 - - [16/Apr/2021 01:24:28] "POST / HTTP/1.1" 200 -
2021-04-16 01:24:29.356034: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 37879808 exceeds 10% of system memory.
[2021-04-16 02:39:10,954][werkzeug][INFO][113]: 10.244.0.1 - - [16/Apr/2021 02:39:10] "POST / HTTP/1.1" 200 -
[2021-04-16 02:39:11,974][werkzeug][INFO][113]: 10.244.0.1 - - [16/Apr/2021 02:39:11] "GET / HTTP/1.1" 405 -
[2021-04-16 02:39:15,764][werkzeug][INFO][113]: 10.244.0.1 - - [16/Apr/2021 02:39:15] "POST / HTTP/1.1" 200 -
[2021-04-16 02:39:16,609][werkzeug][INFO][113]: 10.244.0.1 - - [16/Apr/2021 02:39:16] "POST / HTTP/1.1" 200 -
```

**Comment by llhuii** [comment]
@Jw-Jm According to your provided logs, your unstable networking is the main reason:
1. 200 reponsed some POST requests
2. the error of edge-worker also happened occasionally
3. 405 is the response of your manully curl command
4. And your second curl was refused due to network error

**Comment by llhuii** [comment]
> @Jw-Jm According to your provided logs, your unstable networking is the main reason:
> 
> 2. the error of edge-worker also happened occasionally
>

@Jw-Jm can you help to double check the second item?
If so, I think we could close this one.

**Comment by llhuii** [comment]
For your information, the `NewConnectionError` (edge-worker connecting to cloud-worker) error also occurs at the beginning of edge-worker running, at this time cloud-worker is not ready for serving request.

**Comment by llhuii** [comment]
> For your information, the `NewConnectionError` (edge-worker connecting to cloud-worker) error also occurs at the beginning of edge-worker running, at this time cloud-worker is not ready for serving request.

But not your this case, since cloud-worker was ready at `[2021-04-16 01:17:06,984]` before `NewConnectionError` was reported at `[2021-04-16 02:32:48,383]`

**Comment by llhuii** [comment]
I noticed you run this service for a while, we have a issue in high disk usage for storing hard examples, you may need to check the `/joint_inference/output` disk usage using `du -d 1 -h /joint_inference/output` at node3.

Sorry for this issue recorded here https://github.com/kubeedge/sedna/issues/27#issuecomment-811000454, it will be fixed in this month.

**Comment by llhuii** [comment]
> @Jw-Jm According to your provided logs, your unstable networking is the main reason:
> 
> 1. 200 reponsed some POST requests
> 2. the error of edge-worker also happened occasionally
> 3. 405 is the response of your manully curl command
> 4. And your second curl was refused due to network error

What's your actual network status?

**Comment by Jw-Jm** [comment]
@llhuii   
Thank you for your kind reply. I have tested it and it is indeed as you said.
error logs is caused by network instability.
In fact, I can see some analyzed pictures in the directory(/joint_inference/output/hard_example_cloud_inference_output) of Edge.
by the way, thanks for reminding me of issue #27, I will pay attention on disk usage

**Comment by Jw-Jm** [comment]
My actual scenario is as follows:
two virtual machines in VMware（one master one edge）, network connection is the bridge mode

**Comment by llhuii** [comment]
Thank your response.
I close this now. If you have any question, you can reopen it.
/close
