### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by cgafool** [kubeedge/sedna#56]
https://github.com/kubeedge/sedna/blob/f77563236f29f1827a2069e6d862292defd7030c/pkg/globalmanager/incrementallearningjob.go#L119

It should be ijControllerKind, just like  line 55 defined.

**Comment by llhuii** [comment]
@cgafool Hi, thank you for pointing it out. It is a bug indeed.
But it's weird that it doesn't have the big effect as it should be.

Can you submit a pr for fixing it if you don't mind it?

**Comment by llhuii** [comment]
> But it's weird that it doesn't have the big effect as it should be.

The cases this bug affects are that when the training/eval pod fails to run, GM misses to update the status of `incremental job`.

If the training/eval pod runs successfully, pod calls lib to tell LC, then to GM, then GM sets the status of `incremental job` to **completed**.

**Comment by llhuii** [comment]
Sorry, i will take this for release 0.2.0
