### ISSUE TITLE
How does federated learning server and client communicate through KubeEdge?

### ISSUE THREAD

**Issue by weimingwill** [kubeedge/sedna#62]
Hi,

The server and client of federated learning communicate through `websocket` in the example provided here https://github.com/kubeedge/sedna/blob/d3a647261a5d4dc25a0f4e60bf66adf1f23031f6/lib/sedna/federated_learning/aggregator.py#L122.

While I cannot find the settings that actually bind the IP and Port to environment variables ENV. I am also wondering (1) whether the websocket is through KubeEdge or a separate connection? If it is, (2) how does the websocket actually run connect with KubeEdge network?

Thank you.

**Comment by llhuii** [comment]
>While I cannot find the settings that actually bind the IP and Port to environment variables ENV

setting by federatedLearning controller in gm. 
https://github.com/kubeedge/sedna/blob/d3a647261a5d4dc25a0f4e60bf66adf1f23031f6/pkg/globalmanager/federatedlearningjob.go#L443

> (1) whether the websocket is through KubeEdge or a separate connection? 

A separate connection is used.

**Comment by weimingwill** [comment]
Thanks.
