### ISSUE TITLE
[Incremental Learning] Add the support with different `nodeName` of train/eval workers

### ISSUE THREAD

**Issue by llhuii** [kubeedge/sedna#67]
**What would you like to be added/modified**:
Currently in the feature of incremental learning, the `nodeName`s of dataset and train/eval workers should be same.

When the dataset is in shared storage, the support with different nodeName could be added

**Why is this needed**:
1. In principle we can't require the user must train and eval model in same node.
2. Train requires much more resources than eval worker, they may not in the same node.
3. Sometimes the user may need to do evalution in the same/similar node with infer-worker, such as both at edge.

**Comment by llhuii** [comment]
## How
The ideas:
1. the central is the FSM(finite state machine) translation of a incremental learning job(for short, just using job word below)
2. GM and one LC translate the FSM of a job ==> GM and multi LCs translate the FSM

steps:
1. the user creates a dataset with a nodeName(says node-dataset), and labels the data periodly. And node-dataset's LC monitors the data.
2. the user creates a job using this dataset for incremental learning with training in a node(says node-train), eval in a node(says node-eval).
3. GM syncs this job to node-dataset's LC, this LC picks the incremental data from dataset(step 1), and checks its amount to trigger train worker. If ready to train, this LC saves the dataset to shared storage and sends the ready-to-train state to GM.
4. GM finds this job ready to train, and creates the train worker, also syncs the job info to node-train's LC. After the train worker completes, the worker sends the result to node-train's LC which then sends the ready-to-eval state to GM.
5. GM finds this job ready to eval, and creates the eval worker, also syncs the job info to node-eval's LC. After the eval worker completes, the worker sends the result to node-eval's LC. The LC then compares the eval's results to trigger the model replacement and also sends the eval-complete/deploy-ready state to GM.
6. GM finds this job ready to restart the infer worker, then restart the infer worker.

Fault tolerance:
1. If GM/LCs find any error occours in any stage(train/eval/deploy), it resets to train stage's waiting.

**Comment by llhuii** [comment]
## implementation details
1. downstream controller: GM syncs to the selected LC depending the stage.
2. incremental-learning controller: nothing to change
3. LC: able to reload a job from specified state; check the node of next stage whether changed or not.

**Comment by llhuii** [comment]
![the sequence diagram of the solution](http://www.plantuml.com/plantuml/png/TLF1Rjim3BthAuXUkW5rihINmOUXGm_5i7OOKEoM2sipYJQPyYHwGVz-OfGQSk8OI0ABV8_lFIhtKJ38q3bplHFfOxrSzWvPJnQDxvQH_Wx43LMjnMt0pfXh7CJpqBrICDY83_0hKZ1zeh6DxHCMuEhxvnVu-lFR5M3KtqdryTcST3yz00gqA1X9AlOj7O1F3vzc6oMWvR9jDKz8_z2LRRScFO_FK7rHJJKu6sMvHsbsxxDX2PQRG1sne8FV_jKOTJT27WAX4E08s5lPrR3crGBY7SIU6hknrC8Gt9fl5w3ZVs17zSIUIMHG9L8bhu-Yr2_K4D-u0TdHECBoneDuFKiju7o3Gcqwdb8gUYJfF5lnOSA3d6JrwOtAu-i8KL26UC4fdoQIBQyPrWOcpsgHDmDx7_vGE8HnQ2uMDWDB8UcYpb5wUWbqjz1OA9oZ5F12ZXgrVvBp-FhuNCDXyTG2qrvjJMv6Sp2VHrHvX37E-xuCGssnvQq1AA2HHEDLIWrMm_R70FPefUZNLHNhLe2kEfLrqX4ZmMwt5C16O2yGKMpK2sP0uICBzZrngppgfofLHknwHp5nYuTnq0QGtmn0GfbthfpBSIArDmU3qQ7G9KU1i5MMy-XoFKTN65xD6jR2-_ZjCR-EOiGjmIRuRi9s0sk-B2pVcgnhLfZMptNTpkaoe9MnOOVSkam0WUBWf3O0w0HQwfr_AtTLxcd2Klu3CmmwtvAxAKsDPdB76FF4Jw3K5ZIiwKM53urtRMQjyhIFQeLS960_BqsJdvdFlieIZZT5F-O-VG-T-my0)

**Comment by llhuii** [comment]
Also need to support nodeSelector #44

**Comment by llhuii** [comment]
note:
1. cleanup:  goroutine for the incremental job should be stopped when no needed.

**Comment by JimmyYang20** [comment]
@llhuii delete goroutine when no needed

**Comment by llhuii** [comment]
fixed by #110
/close
