### ISSUE TITLE
The style of the icons in the readme file is not uniform

### ISSUE THREAD

**Issue by Poorunga** [kubeedge/sedna#73]
**What would you like to be added/modified**:

![image](https://user-images.githubusercontent.com/43004096/120255156-eca86b00-c2bd-11eb-9c5b-9ad3df77d007.png)

As you can see, icon `license` is a flat style, which is incompatible with other icons

**Why is this needed**:

**Comment by hardwind-wang** [comment]
good issue. 
we should be nice to OCD patients. :)

**Comment by llhuii** [comment]
fixed by #75
/close
